name: luna-project
dependencies:
  - python=3.10.4
  - psycopg2=2.8.6
  - pip=21.2.4
  - pip:
      - django==4.0.5
      - djangorestframework==3.13.1
      - djangorestframework-simplejwt==5.2.0
      - Pillow==9.1.1
      - flake8==4.0.1
      - gunicorn==20.1.0
      - drf-yasg==1.20.0
      - django-filter==22.1
      - django-cors-headers==3.13.0
